### PR TITLE
[Envoy] Add project.

### PR DESCRIPTION
**Pull request by htuch**
Following the steps at
https://github.com/google/oss-fuzz/blob/master/docs/new_project_guide.md.

Signed-off-by: Harvey Tuch <htuch@google.com>

### CODE REVIEW

**Comment by inferno-chromium** [comment]
@jonathanmetzman - can you please help to review.

**Comment by htuch** [comment]
Yep, the Docker stuff is largely because we started with a copy+paste of `projects/grpc`. Will fix.

On coverage, this is similar to my local experience, I was a bit confused about how I'm supposed to validate locally with pure ASAN and without LLVM coverage generation; see https://github.com/google/oss-fuzz/pull/1126 for the thread. Any assistance here appreciated, it's a bit mysterious to me still how we get coverage without instrumentation.

**Comment by kcc** [comment]
I've built the asan version and it looks fine. 
The coverage is indeed tiny, but that's totally expected from a target that fuzzes base64.
I assume this is just a test target and you will have more. :) 

> Any assistance here appreciated,

I am bit lost. Which part doesn't work after the fix for #1126  ?

**Comment by kcc** [comment]
Interesting. 
Running 
```
./infra/helper.py build_fuzzers envoy 
```
works and produces good asan binary. 

But then running 
```
./infra/helper.py build_fuzzers --sanitizer coverage envoy
```
fails: 
```
external/envoy_deps/thirdparty_build/lib/libcrypto.a(bcm.c.o):bcm.c:function RAND_bytes_with_additional_data: error: undefined reference to '__asan_stack_malloc_4'

```

could this be caused by https://github.com/google/oss-fuzz/pull/1126 ?

**Comment by kcc** [comment]
Yes, undoing https://github.com/google/oss-fuzz/pull/1125/ helps. 
I don't know enough about bazel, but maybe doing `bazel clean` at the top of `build.sh`  would be sufficient 

The coverage build also looks sane. Yes, it shows crazy `INITED cov: 10124` (this is most likely caused different coverage instrumentations used. Should be safe to ignore).

**Comment by kcc** [comment]
Running `./infra/helper.py coverage  envoy base64_fuzz_test`
leads to 
```
Navigate to see coverage: http://127.0.0.1:8001/
```
and a working top-level coverage page, but then 
```
192.168.9.1 - - [01/Feb/2018 22:02:56] "GET /proc/self/cwd/source/common/common/base64.cc HTTP/1.1" 404 -
```

Looks like the local coverage collection is busted (apparently, noone have been using it for a while). 

Anyway, this PR currently looks good to me (modulo comments about docker above). 
Looking forward to seeing real fuzz targets (not just base64).

**Comment by kcc** [comment]
The problem with coverage may also be caused by the pesky "/proc/self/cwd/" which is created by bazel and thus be specific to this PR (and also affect grpc, but not others)

**Comment by htuch** [comment]
OK, great. Thanks for the review feedback @jonathanmetzman and @kcc. I've addressed the `Dockerfile` nits. Yes, we plan on doing more than base64 encoder fuzzing ;) The idea was to get a simple example working end-to-end and then building more complex control and data plane fuzzer binaries once the infrastructure was in place.

**Comment by inferno-chromium** [comment]
Build is failing
https://oss-fuzz-build-logs.storage.googleapis.com/index.html
https://oss-fuzz-build-logs.storage.googleapis.com/log-a2a5bec8-1d76-47b4-8972-bb35e582ded2.txt

@htuch - can you please take a look.

**Comment by kcc** [comment]
I suspect this is related to my comment https://github.com/google/oss-fuzz/pull/1130#issuecomment-362414004 above: 
We either need to revert https://github.com/google/oss-fuzz/pull/1125 (helps) or add `bazel clean` to the `build.sh` (unverified guess)

**Comment by htuch** [comment]
https://github.com/google/oss-fuzz/pull/1133; this was just a convenience for local use, let's drop if broken on build machines.

**Comment by kcc** [comment]
ubsan build fails (--sanitizer undefined): 
```
clang-6.0: error: invalid argument '-fsanitize=vptr' not allowed with '-fno-rtti'
```

This is a common problem. We probably need to fix it eventually in the clang driver.
for now please add -fno-sanitize=vptr as some other projects do.

**Comment by inferno-chromium** [comment]
@htuch - build is still failing, please take a look on Monday. we need to get a first working build, otherwise it raises a ton of exceptions on our infrastructure.

**Comment by htuch** [comment]
@inferno-chromium is it failing on ASAN or UBSAN? I noticed that you've set the project.yaml to only ASAN now.

I built with `python infra/helper.py build_fuzzers --sanitizer=undefined envoy` after your recent changes to `build.sh` to fix `CFLAGS/CXXFLAGS`, it seems to work fine and I can run the fuzzer locally.

Beyond what I can see locally, are there any build debug artifacts you can point me at?

**Comment by inferno-chromium** [comment]
@htuch - i looked at wrong log incorrectly, this seemed to be failure during coverage build (see https://oss-fuzz-build-logs.storage.googleapis.com/index.html), so i have reenabled ubsan now. Also, right now i can build coverage locally fine, so triggered another envoy build on builder, lets see if it succeeds.

**Comment by htuch** [comment]
As a temporary workaround, "bazel clean --expunge" would work, I think we
should fix this properly in Envoy though.

**Comment by inferno-chromium** [comment]
@htuch - ok upto you, we are fine to wait another day till this is fixed properly.

**Comment by htuch** [comment]
@inferno-chromium can we kick off another run, now that https://github.com/envoyproxy/envoy/pull/2534 has merged?

**Comment by inferno-chromium** [comment]
@htuch - done and got first green build, yippee, build page should update in < 30 min, but i checked the results on builder.
