### PR TITLE
native go infra: switch to main branch

### PR DESCRIPTION
**Pull request by AdamKorcz**
Signed-off-by: AdamKorcz <adam@adalogics.com>

### CODE REVIEW

**Review by oliverchang — APPROVED** [review]

**Comment by oliverchang** [comment]
/gcbrun trial_build.py smt helm moby go-dns go-coredns istio --sanitizer address --fuzzing-engine libfuzzer

**Comment by oliverchang** [comment]
It failed for a weird reason: 

```
2022-12-09 06:49:28.053 GMT
Step #1: Step #4: #5 87.61 Installed Go for linux/amd64 in /tmp/go-CodeIntelligenceTesting
2022-12-09 06:49:28.053 GMT
Step #1: Step #4: #5 87.61 Installed commands in /tmp/go-CodeIntelligenceTesting/bin
2022-12-09 06:49:28.053 GMT
Step #1: Step #4: #5 87.61 *** You need to add /tmp/go-CodeIntelligenceTesting/bin to your PATH.
2022-12-09 06:49:28.053 GMT
Step #1: Step #4: #5 87.62 + rm -rf /root/.go
2022-12-09 06:49:28.053 GMT
Step #1: Step #4: #5 88.26 + mv -f /tmp/go-CodeIntelligenceTesting /root/.go
2022-12-09 06:49:28.053 GMT
Step #1: Step #4: #5 88.27 + rm -rf /root/go/
2022-12-09 06:49:28.053 GMT
Step #1: Step #4: #5 88.66 + mkdir -p /root/go/
2022-12-09 06:49:28.053 GMT
Step #1: Step #4: #5 88.66 + go install github.com/CodeIntelligenceTesting/go114-fuzz-build@latest
2022-12-09 06:49:28.053 GMT
Step #1: Step #4: #5 204.7 go: github.com/CodeIntelligenceTesting/go114-fuzz-build@latest: no matching versions for query "latest"
2022-12-09 06:49:28.053 GMT
Step #1: Step #4: #5 ERROR: executor failed running [/bin/sh -c install_go_CodeIntelligenceTesting.sh]: exit code: 1
2022-12-09 06:49:28.053 GMT
Step #1: Step #4: ------
2022-12-09 06:49:28.053 GMT
Step #1: Step #4: > [2/2] RUN install_go_CodeIntelligenceTesting.sh:
```

Trying again.

**Comment by oliverchang** [comment]
/gcbrun trial_build.py smt helm moby go-dns go-coredns istio --sanitizer address --fuzzing-engine libfuzzer

**Comment by oliverchang** [comment]
Only failure now seems to be helm:

```
+ git clone --branch=dev https://github.com/AdamKorcz/go-118-fuzz-build /src/go-118-fuzz-build
Cloning into '/src/go-118-fuzz-build'...
remote: Enumerating objects: 302, done.
remote: Counting objects:   0% (1/112)
remote: Compressing objects:   1% (1/70)
Receiving objects:   0% (1/302)
Receiving objects:  69% (209/302)
Resolving deltas:   0% (0/151)
+ cd /src/helm
+ go mod edit -replace github.com/AdamKorcz/go-118-fuzz-build=/src/go-118-fuzz-build
+ go mod download
+ go mod tidy
+ go get github.com/AdamKorcz/go-118-fuzz-build/testing
go: added github.com/AdamKorcz/go-118-fuzz-build v0.0.0-20221201201421-b019dfef7e3b
+ compile_native_go_fuzzer helm.sh/helm/v3/internal/ignore FuzzIgnoreParse fuzz_ignore_parse
# command-line-arguments
./main.3430454606.go:29:44: undefined: testing.NewT
./main.3430454606.go:30:15: fuzzer.CleanupTempDirs undefined (type *"github.com/AdamKorcz/go-118-fuzz-build/testing".F has no field or method CleanupTempDirs)
2022/12/12 00:09:47 failed to build packages:exit status 2
```

@AdamKorcz any ideas why?

**Comment by oliverchang** [comment]
Friendly ping @AdamKorcz !

**Comment by AdamKorcz** [comment]
Thanks for the ping @oliverchang. The failure should be resolved by https://github.com/cncf/cncf-fuzzing/pull/248.

**Comment by oliverchang** [comment]
/gcbrun trial_build.py smt helm moby go-dns go-coredns istio --sanitizer address --fuzzing-engine libfuzzer
